import { BootstrapRepoManager } from "@api/database/BootstrapRepoManager"
import { CollectionMetadataModel, FieldMetadataModel, RelationMetadataModel } from "@zmaj-js/common"

export async function configureBlogInfra(repoManager: BootstrapRepoManager, trx: any) {
	const repo = repoManager.getRepo(FieldMetadataModel)
	const repoCol = repoManager.getRepo(CollectionMetadataModel)
	const repoRel = repoManager.getRepo(RelationMetadataModel)

	console.log("running")

	await repoCol.createMany({
		trx,
		overrideCanCreate: true,
		data: [
			{
				id: "9016e056-f094-4476-a62b-53b246ff4bd2",
				createdAt: new Date("2023-04-05T19:48:09.528Z"),
				tableName: "posts",
				collectionName: "posts",
				disabled: false,
				label: null,
				hidden: false,
				displayTemplate: "{title}",
				layoutConfig: {},
			},
			{
				id: "64bf9570-e5c6-49b0-bac9-a832b48a0ee5",
				createdAt: new Date("2023-04-05T19:48:09.528Z"),
				tableName: "comments",
				collectionName: "comments",
				disabled: false,
				label: null,
				hidden: false,
				displayTemplate: "{body|truncate}",
				layoutConfig: {},
			},
			{
				id: "fb242708-79a4-4a74-91ee-fb266196e8d0",
				createdAt: new Date("2023-04-05T19:48:09.528Z"),
				tableName: "posts_tags",
				collectionName: "postsTags",
				disabled: false,
				label: null,
				hidden: false,
				displayTemplate: null,
				layoutConfig: {},
			},
			{
				id: "19050b27-cc49-4484-aa9e-a0b29305ed1d",
				createdAt: new Date("2023-04-05T19:48:09.528Z"),
				tableName: "tags",
				collectionName: "tags",
				disabled: false,
				label: null,
				hidden: false,
				displayTemplate: "{name}",
				layoutConfig: {},
			},
			{
				id: "da894552-574f-4dda-99c4-ed2fcf1ae4f5",
				createdAt: new Date("2023-04-05T19:48:09.528Z"),
				tableName: "posts_info",
				collectionName: "postsInfo",
				disabled: false,
				label: null,
				hidden: false,
				displayTemplate: null,
				layoutConfig: {},
			},
		],
	})

	await repo.createMany({
		trx,
		overrideCanCreate: true,
		data: [
			{
				id: "29076deb-56eb-4119-941f-6ed34ff61861",
				createdAt: new Date("2023-04-05T19:48:09.598Z"),
				columnName: "id",
				tableName: "posts",
				fieldName: "id",
				canCreate: true,
				canUpdate: false,
				canRead: true,
				sortable: true,
				label: "Id",
				componentName: null,
				displayTemplate: null,
				description: null,
				fieldConfig: {},
				isUpdatedAt: false,
				isCreatedAt: false,
			},
			{
				id: "e5e7a065-9e90-438c-9eb6-a63732b74def",
				createdAt: new Date("2023-04-05T19:48:09.598Z"),
				columnName: "created_at",
				tableName: "posts",
				fieldName: "createdAt",
				canCreate: true,
				canUpdate: true,
				canRead: true,
				sortable: true,
				label: "Created At",
				componentName: null,
				displayTemplate: null,
				description: null,
				fieldConfig: {},
				isUpdatedAt: false,
				isCreatedAt: false,
			},
			{
				id: "1abf10bd-f27b-46d6-9813-2cecdf800b70",
				createdAt: new Date("2023-04-05T19:48:09.598Z"),
				columnName: "title",
				tableName: "posts",
				fieldName: "title",
				canCreate: true,
				canUpdate: true,
				canRead: true,
				sortable: true,
				label: "Title",
				componentName: null,
				displayTemplate: null,
				description: null,
				fieldConfig: {},
				isUpdatedAt: false,
				isCreatedAt: false,
			},
			{
				id: "31cfc28c-09b7-4df9-bf2e-07d8f02fa4e1",
				createdAt: new Date("2023-04-05T19:48:09.598Z"),
				columnName: "body",
				tableName: "posts",
				fieldName: "body",
				canCreate: true,
				canUpdate: true,
				canRead: true,
				sortable: true,
				label: "Body",
				componentName: "markdown",
				displayTemplate: null,
				description: null,
				fieldConfig: {},
				isUpdatedAt: false,
				isCreatedAt: false,
			},
			{
				id: "61416ed8-eea6-451b-9967-7cb20abf4035",
				createdAt: new Date("2023-04-05T19:48:09.598Z"),
				columnName: "likes",
				tableName: "posts",
				fieldName: "likes",
				canCreate: true,
				canUpdate: true,
				canRead: true,
				sortable: true,
				label: "Likes",
				componentName: null,
				displayTemplate: null,
				description: null,
				fieldConfig: {},
				isUpdatedAt: false,
				isCreatedAt: false,
			},
			{
				id: "08983405-485a-4798-98a8-974f32e4086a",
				createdAt: new Date("2023-04-05T19:48:09.598Z"),
				columnName: "id",
				tableName: "comments",
				fieldName: "id",
				canCreate: true,
				canUpdate: false,
				canRead: true,
				sortable: true,
				label: "Id",
				componentName: null,
				displayTemplate: null,
				description: null,
				fieldConfig: {},
				isUpdatedAt: false,
				isCreatedAt: false,
			},
			{
				id: "80eaa1e2-1ef5-41ff-a0c2-d303023b0328",
				createdAt: new Date("2023-04-05T19:48:09.598Z"),
				columnName: "body",
				tableName: "comments",
				fieldName: "body",
				canCreate: true,
				canUpdate: true,
				canRead: true,
				sortable: true,
				label: "Body",
				componentName: null,
				displayTemplate: null,
				description: null,
				fieldConfig: {},
				isUpdatedAt: false,
				isCreatedAt: false,
			},
			{
				id: "8efbedea-783b-4d50-b210-fe0d9c7ad243",
				createdAt: new Date("2023-04-05T19:48:09.598Z"),
				columnName: "post_id",
				tableName: "comments",
				fieldName: "postId",
				canCreate: true,
				canUpdate: true,
				canRead: true,
				sortable: true,
				label: "Post Id",
				componentName: null,
				displayTemplate: null,
				description: null,
				fieldConfig: {},
				isUpdatedAt: false,
				isCreatedAt: false,
			},
			{
				id: "ea330eb8-238b-4642-a5b5-8f02944652e2",
				createdAt: new Date("2023-04-05T19:48:09.598Z"),
				columnName: "id",
				tableName: "posts_tags",
				fieldName: "id",
				canCreate: true,
				canUpdate: false,
				canRead: true,
				sortable: true,
				label: "Id",
				componentName: null,
				displayTemplate: null,
				description: null,
				fieldConfig: {},
				isUpdatedAt: false,
				isCreatedAt: false,
			},
			{
				id: "10e9ad68-974f-4a54-9cc1-a97ea1fe7587",
				createdAt: new Date("2023-04-05T19:48:09.598Z"),
				columnName: "post_id",
				tableName: "posts_tags",
				fieldName: "postId",
				canCreate: true,
				canUpdate: true,
				canRead: true,
				sortable: true,
				label: "Post Id",
				componentName: null,
				displayTemplate: null,
				description: null,
				fieldConfig: {},
				isUpdatedAt: false,
				isCreatedAt: false,
			},
			{
				id: "bad693ba-26e7-4b92-8919-755c8dc789ec",
				createdAt: new Date("2023-04-05T19:48:09.598Z"),
				columnName: "tag_id",
				tableName: "posts_tags",
				fieldName: "tagId",
				canCreate: true,
				canUpdate: true,
				canRead: true,
				sortable: true,
				label: "Tag Id",
				componentName: null,
				displayTemplate: null,
				description: null,
				fieldConfig: {},
				isUpdatedAt: false,
				isCreatedAt: false,
			},
			{
				id: "dc4251cd-69d4-4f87-aaf8-fafed52dcbf2",
				createdAt: new Date("2023-04-05T19:48:09.598Z"),
				columnName: "id",
				tableName: "tags",
				fieldName: "id",
				canCreate: true,
				canUpdate: false,
				canRead: true,
				sortable: true,
				label: "Id",
				componentName: null,
				displayTemplate: null,
				description: null,
				fieldConfig: {},
				isUpdatedAt: false,
				isCreatedAt: false,
			},
			{
				id: "561c7fc7-2d93-477d-bf63-595e341b295b",
				createdAt: new Date("2023-04-05T19:48:09.598Z"),
				columnName: "name",
				tableName: "tags",
				fieldName: "name",
				canCreate: true,
				canUpdate: true,
				canRead: true,
				sortable: true,
				label: "Name",
				componentName: null,
				displayTemplate: null,
				description: null,
				fieldConfig: {},
				isUpdatedAt: false,
				isCreatedAt: false,
			},
			{
				id: "de11e686-5ef3-41b4-843b-73c02e04b91f",
				createdAt: new Date("2023-04-05T19:48:09.598Z"),
				columnName: "id",
				tableName: "posts_info",
				fieldName: "id",
				canCreate: true,
				canUpdate: false,
				canRead: true,
				sortable: true,
				label: "Id",
				componentName: null,
				displayTemplate: null,
				description: null,
				fieldConfig: {},
				isUpdatedAt: false,
				isCreatedAt: false,
			},
			{
				id: "fb128dff-904e-4595-9113-5224621ad7ea",
				createdAt: new Date("2023-04-05T19:48:09.598Z"),
				columnName: "post_id",
				tableName: "posts_info",
				fieldName: "postId",
				canCreate: true,
				canUpdate: true,
				canRead: true,
				sortable: true,
				label: "Post Id",
				componentName: null,
				displayTemplate: null,
				description: null,
				fieldConfig: {},
				isUpdatedAt: false,
				isCreatedAt: false,
			},
			{
				id: "470925ee-5453-457e-b435-682642b1709e",
				createdAt: new Date("2023-04-05T19:48:09.598Z"),
				columnName: "additional_info",
				tableName: "posts_info",
				fieldName: "additionalInfo",
				canCreate: true,
				canUpdate: true,
				canRead: true,
				sortable: true,
				label: "Additional Info",
				componentName: null,
				displayTemplate: null,
				description: null,
				fieldConfig: {},
				isUpdatedAt: false,
				isCreatedAt: false,
			},
		],
	})

	await repoRel.createMany({
		trx,
		overrideCanCreate: true,
		data: [
			{
				id: "a653e54a-6f42-445f-9694-050cfa58464b",
				createdAt: new Date("2023-04-05T19:48:09.618Z"),
				tableName: "comments",
				fkName: "comments_post_id_fkey",
				mtmFkName: null,
				propertyName: "post",
				template: null,
				label: "Post",
				hidden: false,
			},
			{
				id: "c53134a6-5cd1-4148-9ad5-71cc4fe97094",
				createdAt: new Date("2023-04-05T19:48:09.618Z"),
				tableName: "posts",
				fkName: "comments_post_id_fkey",
				mtmFkName: null,
				propertyName: "comments",
				template: null,
				label: "Comments",
				hidden: false,
			},
			{
				id: "d8cb4230-216e-4d36-8d03-de83e4a97329",
				createdAt: new Date("2023-04-05T19:48:09.618Z"),
				tableName: "posts_info",
				fkName: "posts_info_post_id_fkey",
				mtmFkName: null,
				propertyName: "post",
				template: null,
				label: "Post",
				hidden: false,
			},
			{
				id: "596f92c1-9476-4f76-8949-03d3220b9dea",
				createdAt: new Date("2023-04-05T19:48:09.618Z"),
				tableName: "posts",
				fkName: "posts_info_post_id_fkey",
				mtmFkName: null,
				propertyName: "postInfo",
				template: null,
				label: "Post Info",
				hidden: false,
			},
			{
				id: "f05b74e7-3d7f-405a-88d3-bb3057968c83",
				createdAt: new Date("2023-04-05T19:48:09.618Z"),
				tableName: "posts_tags",
				fkName: "posts_tags_post_id_fkey",
				mtmFkName: null,
				propertyName: "post",
				template: null,
				label: "Post",
				hidden: false,
			},
			{
				id: "58d9e7ba-c4e1-497a-b18d-084a42638100",
				createdAt: new Date("2023-04-05T19:48:09.618Z"),
				tableName: "posts",
				fkName: "posts_tags_post_id_fkey",
				mtmFkName: "posts_tags_tag_id_fkey",
				propertyName: "tags",
				template: null,
				label: "Tags",
				hidden: false,
			},
			{
				id: "7f20a9ef-57fc-4ca7-9355-bfe14b60ea7b",
				createdAt: new Date("2023-04-05T19:48:09.618Z"),
				tableName: "posts_tags",
				fkName: "posts_tags_tag_id_fkey",
				mtmFkName: null,
				propertyName: "tag",
				template: null,
				label: "Tag",
				hidden: false,
			},
			{
				id: "5e458d8a-ad7c-4ac5-bf09-e946fe6c0e6a",
				createdAt: new Date("2023-04-05T19:48:09.618Z"),
				tableName: "tags",
				fkName: "posts_tags_tag_id_fkey",
				mtmFkName: "posts_tags_post_id_fkey",
				propertyName: "posts",
				template: null,
				label: "Posts",
				hidden: false,
			},
		],
	})

	// posts

	// await repoCol.updateWhere({
	// 	where: { tableName: "posts" },
	// 	changes: { displayTemplate: "{title}" },
	// 	trx,
	// })
	// await repo.updateWhere({
	// 	where: { tableName: "posts", columnName: "likes" as keyof TPost },
	// 	changes: { componentName: "int" },
	// 	trx,
	// })
	// await repoRel.updateWhere({
	// 	where: { tableName: "posts", propertyName: "postsTags" },
	// 	changes: new RelationUpdateDto({ propertyName: "tags", label: "Tags" }),
	// 	trx,
	// })
	// await repo.updateWhere({
	// 	where: { tableName: "posts", columnName: "body" },
	// 	changes: { componentName: "long-text" },
	// 	trx,
	// })

	// // comments
	// await repoCol.updateWhere({
	// 	where: { tableName: "comments" },
	// 	changes: { displayTemplate: "{body}" },
	// 	trx,
	// })
	// await repo.updateWhere({
	// 	where: { tableName: "comments", columnName: "body" as keyof TComment },
	// 	changes: { componentName: "markdown" },
	// 	trx,
	// })

	// // tags
	// await repoCol.updateWhere({
	// 	where: { tableName: "tags" },
	// 	changes: { displayTemplate: "{name}" },
	// 	trx,
	// })

	// // post_info
	// await repo.updateWhere({
	// 	where: { tableName: "post_info", columnName: "additionalInfo" as keyof TPostInfo },
	// 	changes: { componentName: "key-value" },
	// 	trx,
	// })

	// // posts_tags
	// await repoRel.updateWhere({
	// 	where: { tableName: "tags", propertyName: "postsTags" },
	// 	changes: new RelationUpdateDto({ propertyName: "posts", label: "Posts" }),
	// 	trx,
	// })

	// await repoRel.updateWhere({
	// 	where: { tableName: "posts", propertyName: "postsTags" },
	// 	changes: new RelationUpdateDto({ propertyName: "tags", label: "Tags" }),
	// 	trx,
	// })
}
