version: "3.9"

services:
  redis:
    image: docker.io/redis:7-alpine
    restart: unless-stopped
    ports:
      - ${DCU_REDIS_PORT:?err}:6379

  database:
    image: docker.io/postgres:15-alpine
    restart: unless-stopped
    ports:
      - ${DB_PORT:?err}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME:?err}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?err}
      POSTGRES_DB: ${DB_DATABASE:?err}
    volumes:
      - db_volume:/var/lib/postgresql/data

  storage:
    image: docker.io/minio/minio
    restart: unless-stopped
    # command: server /data --console-address ":36505"
    command: server /data --console-address ":${DCU_MINIO_GUI_PORT:?err}"
    environment:
      MINIO_ROOT_USER: ${STORAGE_PROVIDERS__MINIO__ACCESS_KEY:?err}
      MINIO_ROOT_PASSWORD: ${STORAGE_PROVIDERS__MINIO__SECRET_KEY:?err}
      MINIO_REGION_NAME: ${STORAGE_PROVIDERS__MINIO__REGION:?err}
    volumes:
      - storage_volume:/data
    ports:
      - ${DCU_MINIO_PORT:?err}:9000
      - ${DCU_MINIO_GUI_PORT:?err}:36505

  # enables email testing without external testing service
  email:
    image: docker.io/mailhog/mailhog
    restart: unless-stopped
    ports:
      - ${EMAIL_PORT:?err}:1025
      - ${DCU_EMAIL_GUI_PORT:?err}:8025

volumes:
  db_volume:
    name: ${DCU_DB_VOLUME:?err}
  storage_volume:
    name: ${DCU_STORAGE_VOLUME:?err}
