import {
	ActivityLogModel,
	AuthSessionModel,
	CollectionMetadataModel,
	DbMigrationModel,
	FieldMetadataModel,
	FileModel,
	KeyValueModel,
	PermissionModel,
	RelationMetadataModel,
	RoleModel,
	TranslationModel,
	UserModel,
	WebhookModel,
} from "./modules"

export const systemModels = [
	UserModel,
	RoleModel,
	PermissionModel,
	WebhookModel,
	AuthSessionModel,
	TranslationModel,
	KeyValueModel,
	CollectionMetadataModel,
	FieldMetadataModel,
	FileModel,
	ActivityLogModel,
	RelationMetadataModel,
	DbMigrationModel,
] as const
