version: "3.9"

services:
  database:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: zmaj_db
    volumes:
      - db_volume:/var/lib/postgresql/data

  email:
    image: mailhog/mailhog
    ports:
      # SMTP port
      - 1025:1025
      # HTTP port to see sent emails
      - 8025:8025

volumes:
  db_volume:
