name: Publish
on:
  push:
    tags: ["*"]
  # This bellow does not run.
  # It's good enough, since I will publish package only if CI is successful
  # Check in the future
  # workflow_run:
  #   workflows: ["CI"]
  #   tags: ["*"]
  #   types:
  #     - completed

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Build Success
        run: echo "Build Success"

  publish-npm:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      # https://github.com/pnpm/pnpm/issues/3141#issuecomment-1305563972
      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish packages
        run: pnpm publish --r --access=public --tag latest --no-git-checks

  publish-docker:
    needs: [build]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: Public semver docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: astanisic/zmaj
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          default_branch: main
          tag_semver: true

      - name: Public semver docker image to GitHub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: apstanisic/zmaj/zmaj
          username: ${{ github.actor }}
          password: ${{ secrets.PUBLISH_PACKAGE_TO_GH_TOKEN }}
          default_branch: main
          tag_semver: true
          registry: ghcr.io
